kind: Deployment 
apiVersion: extensions/v1beta1
metadata:
  namespace: default 
  name: gossip-dev 
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        component: gossip-dev
    spec:
      serviceAccountName: admin
      nodeSelector:
        kubernetes.io/hostname: 192.168.100.161 
      containers:
        - name: gossip-dev
          image: gmt.reg.me/test/gossip-dev:v1
          imagePullPolicy: Always
          env:
            - name: SVC 
              value: gossip-dev-headless
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
